#preload = /home/user/Pictures/wallpaper/NGE128.png
#preload = /home/user/Pictures/wallpaper/NGE431.jpg

#wallpaper = DP-1, /home/user/Pictures/wallpaper/NGE128.png
#wallpaper = HDMI-A-1, /home/user/Pictures/wallpaper/NGE431.jpg

wallpaper {
    monitor = DP-1
    path = /home/user/Pictures/wallpaper/NGE128.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/user/Pictures/wallpaper/NGE431.jpg
    fit_mode = cover
}

splash = false
